### ISSUE TITLE
[health 2.0.9] Multiple async calls to requestAuthorization() cause app to crash (on Android only)

### ISSUE THREAD

**Issue by carlleeswanson** [cph-cachet/flutter-plugins#232]
### Device / Emulator and OS
Presumably affects all Android devices/emulators. I tested with 
Pixel 2, 3, 4 (devices & emulators).
AndroidStudio 3.6, 4.1
Flutter 1.17, 1.20, 1.22
health 2.0.6, 2.0.9

### Describe the bug
This only occurs with the Android interface to Google Fit. It is not a problem with the iOS interface to Apple Health.
It appears that concurrent asynchronous calls to health.requestAuthorization() cause entire app to crash.

### To Reproduce
In my app's startup, I make an initial call to requestAuthorization(), passing the list of all HealthDataTypes to be used by the app: [HEART_RATE, WEIGHT, BLOOD_PRESSURE_SYSTOLIC, BLOOD_PRESSURE_DIASTOLIC]. As expected, this causes the Google permissions screen/dialog to present, prompting for username to authorize permissions for. This appears to complete successfully.

However, my app later needs to asynchronously read data for each of these HealthDataTypes, which are displayed in various widgets. To optimize performance, each widget needs to make its own call to health.getDataFromTypes() to read just that widget's data for a single HealthDataType (passed as a list with one element).  (eg. I have one widget that reads/shows latest Heart Rate, another widget that read/shows Weight history).  health.getDataFromTypes() of course calls health.requestAuthorization() passing the same list with one element. Unfortunately, the plugin gets confused by the multiple requests and actually crashes the whole app!

I discovered that if I put a breakpoint on line 27 in health_factory.dart (the line before the async call to _channel.invokeMethod("requestAuthorization")), and simply press "continue" each time execution stops there, the problem goes away (i.e. each of the reads complete successfully). I'm guessing that the stops at the breakpoint introduce enough delay that each async request can complete without clashing with the other(s).

The problem exists across various versions of health, flutter, and AndroidStudio. I've upgraded to the latest of each and the problem still persists.

Sorry, I'm not familiar enough with kotlin or native development to devise a fix and make a pull request. It does appear that the problem may be HealthPlugin.kt, in the method call to requestAuthorization().
I'm a little confused by the java-produced errors (see below), since it appears that the plugin is written in kotlin.

To assist in narrowing the location of the problem, I added a try/catch block and some simple print statements to health_factory.dart for the logs below:`

    List<String> keys = types.map((e) => _enumToString()).toList(); // Put the breakpoint on this line
    try {
      print('HEALTH_DEBUG: health_factory.requestAuthorization($keys)');
      final bool isAuthorized = await _channel.invokeMethod('requestAuthorization', {'types': keys});
      print('HEALTH_DEBUG: health_factory.requestAuthorization($keys) - Authorized: $isAuthorized');
      return isAuthorized;
    } catch (e) {
      print('HEALTH_DEBUG: health_factory.requestAuthorization($keys) error: $e');
      rethrow;
    }`

### Actual behavior
**Console log w/o breakpoint:**
I/flutter (31470): Health requestPermissions dataTypes: [HealthDataType.HEART_RATE, HealthDataType.WEIGHT, HealthDataType.BLOOD_PRESSURE_SYSTOLIC, HealthDataType.BLOOD_PRESSURE_DIASTOLIC]
I/flutter (31470): HEALTH_DEBUG: health_factory.requestAuthorization([HEART_RATE, WEIGHT, BLOOD_PRESSURE_SYSTOLIC, BLOOD_PRESSURE_DIASTOLIC])
D/FLUTTER_HEALTH(31470): Access Granted!
I/flutter (31470): HEALTH_DEBUG: health_factory.requestAuthorization([HEART_RATE, WEIGHT, BLOOD_PRESSURE_SYSTOLIC, BLOOD_PRESSURE_DIASTOLIC]) - Authorized: true
I/flutter (31470): Health requestPermissions: success
I/flutter (31470): WearableDataApi grantAccess Instance of 'SharedHealthApiService': success
I/flutter (31470): HEALTH_DEBUG: health_factory.requestAuthorization([HEART_RATE])
I/flutter (31470): HEALTH_DEBUG: health_factory.requestAuthorization([WEIGHT])
I/flutter (31470): HEALTH_DEBUG: health_factory.requestAuthorization([BLOOD_PRESSURE_SYSTOLIC])
I/flutter (31470): HEALTH_DEBUG: health_factory.requestAuthorization([BLOOD_PRESSURE_DIASTOLIC])
D/FLUTTER_HEALTH(31470): Access Denied!
D/FLUTTER_HEALTH(31470): Access Denied!
D/AndroidRuntime(31470): Shutting down VM
E/AndroidRuntime(31470): FATAL EXCEPTION: main
E/AndroidRuntime(31470): Process: com.carlleeswanson.my_app, PID: 31470
E/AndroidRuntime(31470): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1111, result=0, data=Intent { (has extras) }} to activity {com.carlleeswanson.my_app/com.carlleeswanson.my_app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31470):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
E/AndroidRuntime(31470):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
E/AndroidRuntime(31470):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(31470):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(31470):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(31470):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(31470):     at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31470):     at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(31470):     at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(31470):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31470):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(31470):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(31470): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31470):     at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(31470):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(31470):     at cachet.plugins.health.HealthPlugin.onActivityResult(HealthPlugin.kt:97)
E/AndroidRuntime(31470):     at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(31470):     at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(31470):     at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
E/AndroidRuntime(31470):     at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
E/AndroidRuntime(31470):     at android.app.Activity.dispatchActivityResult(Activity.java:8310)
E/AndroidRuntime(31470):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
E/AndroidRuntime(31470):     ... 11 more
I/Process (31470): Sending signal. PID: 31470 SIG: 9
Lost connection to device.

**Console log w/ breakpoint @ line 27:**
I/flutter (32235): Health requestPermissions dataTypes: [HealthDataType.HEART_RATE, HealthDataType.WEIGHT, HealthDataType.BLOOD_PRESSURE_SYSTOLIC, HealthDataType.BLOOD_PRESSURE_DIASTOLIC]
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([HEART_RATE, WEIGHT, BLOOD_PRESSURE_SYSTOLIC, BLOOD_PRESSURE_DIASTOLIC])
D/FLUTTER_HEALTH(32235): Access Granted!
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([HEART_RATE, WEIGHT, BLOOD_PRESSURE_SYSTOLIC, BLOOD_PRESSURE_DIASTOLIC]) - Authorized: true
I/flutter (32235): Health requestPermissions: success
I/flutter (32235): WearableDataApi grantAccess Instance of 'SharedHealthApiService': success
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([HEART_RATE])
D/FLUTTER_HEALTH(32235): Access Granted!
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([WEIGHT])
D/FLUTTER_HEALTH(32235): Access Granted!
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([BLOOD_PRESSURE_SYSTOLIC])
D/FLUTTER_HEALTH(32235): Access Granted!
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([BLOOD_PRESSURE_DIASTOLIC])
D/FLUTTER_HEALTH(32235): Access Granted!
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([HEART_RATE]) - Authorized: true
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([WEIGHT]) - Authorized: true
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([BLOOD_PRESSURE_SYSTOLIC]) - Authorized: true
I/flutter (32235): HEALTH_DEBUG: health_factory.requestAuthorization([BLOOD_PRESSURE_DIASTOLIC]) - Authorized: true
I/System.out(32235): HEART_RATE
I/System.out(32235): WEIGHT
I/System.out(32235): BLOOD_PRESSURE_SYSTOLIC
I/System.out(32235): BLOOD_PRESSURE_DIASTOLIC
I/flutter (32235): WearableDataApi readData(WearableDataType.BLOOD_PRESSURE_DIASTOLIC): success
I/flutter (32235): WearableDataApi readData(WearableDataType.BLOOD_PRESSURE_SYSTOLIC): success
I/flutter (32235): WearableDataApi readData(WearableDataType.WEIGHT): success
I/flutter (32235): WearableDataApi readData(WearableDataType.HEART_RATE): success

### Flutter doctor 
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.22.4 at C:\Programs\flutter
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Carl\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Users\Carl\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Pixel 2 (mobile) • FA79D1A00418 • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.

**Comment by thomasnilsson** [comment]
Its all related to https://github.com/cph-cachet/flutter-plugins/issues/229

There has been good progress, but the update is not out yet.

**Comment by carlleeswanson** [comment]
@thomasnilsson, Super! Thanks for the update.

**Comment by thomasnilsson** [comment]
Check Health version 3.0.0 - the issue should now be fixed. 

Beware that you now have to request access manually before reading the data.

**Comment by carlleeswanson** [comment]
Yes, it seems to be working fine now with v3.0.0.

Thank you for resolving!

**Comment by oakmad** [comment]
Just an FYI and for future reference but I can make this happen with v3.0.0 by kicking off the requestAuthorization process after its already running. I'm working around it by using a bool to check if I'm already running a sync process (essentially requestAuthorization) before calling again. 

`
E/AndroidRuntime( 7943): FATAL EXCEPTION: main
E/AndroidRuntime( 7943): Process: com.myapp, PID: 7943
E/AndroidRuntime( 7943): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1111, result=-1, data=Intent { (has extras) }} to activity {com.myapp/io.flutter.embedding.android.FlutterActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7943): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4873)
E/AndroidRuntime( 7943): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4914)
E/AndroidRuntime( 7943): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 7943): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 7943): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 7943): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2041)
E/AndroidRuntime( 7943): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 7943): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 7943): 	at android.app.ActivityThread.main(ActivityThread.java:7386)
E/AndroidRuntime( 7943): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7943): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 7943): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
E/AndroidRuntime( 7943): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7943): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime( 7943): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime( 7943): 	at cachet.plugins.health.HealthPlugin.onActivityResult(HealthPlugin.kt:94)
E/AndroidRuntime( 7943): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime( 7943): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime( 7943): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
E/AndroidRuntime( 7943): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
E/AndroidRuntime( 7943): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime( 7943): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4866)
E/AndroidRuntime( 7943): 	... 11 more
`
