### ISSUE TITLE
Get steps for a date

### ISSUE THREAD

**Issue by billymahmood** [cph-cachet/flutter-plugins#36]
Hey,

Great plugin, seems to work well - I just wanted to know if it's possible to get steps for a given date, like yesterdays date.

The reason I ask is - I want to show a weekly / monthly summary for each day - so being able to query would be great, I know I can store the steps for each day in a database however it's getting the steps in the 1st place that I need to resolve.

Thank you,

**Comment by thomasnilsson** [comment]
Glad you like it! 

What you describe is possible on the iOS side, because it just queries Apple Health, but the Android implementation works slightly differently, and it won't be possible as it is.

For what you want I think you are better off using an Apple HealthKit/Google Fit plugin such as https://pub.dev/packages/flutter_health

**Comment by billy124** [comment]
Thank you pal, I will have a play with Flutter Health, seems like a good shout

**Comment by amitbdethe** [comment]
I got the steps data from Google Fitness api for any day that I want. 
they have explained the android/Json implementation in the documentations.

**Comment by thomasnilsson** [comment]
We have now written our own plugin for Google Fit and Apple Health. Feel free to check it out. https://github.com/cph-cachet/flutter-plugins/tree/master/packages/health
