### ISSUE TITLE
[health 3.3.1] weight returned in pounds with unit of kilograms

### ISSUE THREAD

**Issue by matthiasn** [cph-cachet/flutter-plugins#460]
### Device and OS
 - Device: iPhone 12 pro
 - OS: iOS 15.1

### Problem when importing weight
Up until version `3.2.1`, when I imported weight, I received a sample like this one:

```
{
  "value": 100.0,
  "data_type": "weight",
  "unit": "kilograms",
  "date_from": "2021-11-13 15:50:33",
  "date_to": "2021-11-13 15:50:33",
  "platform_type": "ios",
  "device_id": "********-****-****-****-************",
  "source_id": "com.withings.wiScaleNG",
  "source_name": "Health Mate"
}
```

After updating to `3.3.1` however, it looks like this:

```
{
  "value": 220.462,
  "data_type": "weight",
  "unit": "kilograms",
  "date_from": "2021-11-19 09:26:15",
  "date_to": "2021-11-19 09:26:15",
  "platform_type": "ios",
  "device_id": "********-****-****-****-************",
  "source_id": "com.withings.wiScaleNG",
  "source_name": "Health Mate"
}
```

I replaced the values (my weight is irrelevant) while retaining the ratio between before and after. The result is now clearly in `pounds` while still indicating `kilograms`. I found that for iOS, the `HKUnit` is indeed [initialized](https://github.com/cph-cachet/flutter-plugins/blob/master/packages/health/ios/Classes/SwiftHealthPlugin.swift#L256) as `pound`, whereas in the Dart code, it is [specified as kilograms](https://github.com/cph-cachet/flutter-plugins/blob/master/packages/health/lib/src/data_types.dart#L129). I wonder how this could have worked with consistent units in a fairly recent version such as `3.2.1`, since I didn't see any recent unit-related changes.

**Comment by matsunanaro** [comment]
The use of Imperial units was introduced In a [commit](https://github.com/cph-cachet/flutter-plugins/pull/182/commits/8a9b10a3e5e92ef7bffa0c249a3e1efe13ba6b88) of  PR #182 by Matthew-Pitzer, I tried to revert it back to metric units in this [commit](https://github.com/cph-cachet/flutter-plugins/pull/430/commits/0e6dac3774d1c31dce3fd9ef0156cec177f51284?authenticity_token=5GnkxJEEPD6dCb59NHBytYozIPFlDfPmZze6ZEQOAykxn5uD%2BKNu%2F9%2F5%2FDnNAajw4cNcV2V9qGPLb0f4uB75Bg%3D%3D&file-filters%5B%5D=.dart) of PR #430. But the changes was only done with the DART files involved. Obviously it was not good enough, because its Swift implementation needs to be changed too.

**Comment by matsunanaro** [comment]
I've created PR #462 to fix this issue.

**Comment by matthiasn** [comment]
@matsunanaro great thanks, will update once the PR is merged and released.

**Comment by denkoul** [comment]
Same problem here

**Comment by matthiasn** [comment]
I just upgraded and can confirm that it now works as expected. Thanks!
