### ISSUE TITLE
carp_background_location 3.0.1

### ISSUE THREAD

**Issue by sinanhaci** [cph-cachet/flutter-plugins#510]
**Device**

Tried multiple android devices and emulators

**Describe the bug**

See this output this console => `sendLocationEvent {callback=-1061875361058510012, location={altitude=158.6999969482422, heading=233.0393, latitude=40.2325217, accuracy=14.901, speed_accuracy=0.0, time=1.646385464289E12, is_mocked=false, speed=0.28020927, longitude=29.0615565}}`

However, this code block does not return any value to me => `locationSubscription = locationStream?.listen(onData);`

When I copy your sample application exactly, the result is still the same. Am I missing something? What I want to do is to post the incoming data to an API.

**Comment by MohammadElKhatib** [comment]
Same to me any resolution?

**Comment by sinanhaci** [comment]
Unfortunately I couldn't find a solution.

**Comment by devhci** [comment]
I think no data is being passed over the platform channel from the native Android side. The log is coming  from  ''IsolateHolderService.kt" file

**Comment by hector1980** [comment]
In <flutter-directory>\.pub-cache\hosted\pub.dartlang.org\background_locator-1.6.12\lib\location_dto.dart, I have modified the LocationDto.fromJson function as follows.

  factory LocationDto.fromJson(Map<dynamic, dynamic> json) {
    bool? isLocationMocked =
        Platform.isAndroid ? json[Keys.ARG_IS_MOCKED] : false;
    return LocationDto._(
      json[Keys.ARG_LATITUDE] ?? 0.0,
      json[Keys.ARG_LONGITUDE] ?? 0.0,
      json[Keys.ARG_ACCURACY] ?? 0.0,
      json[Keys.ARG_ALTITUDE] ?? 0.0,
      json[Keys.ARG_SPEED] ?? 0.0,
      json[Keys.ARG_SPEED_ACCURACY] ?? 0.0,
      json[Keys.ARG_HEADING] ?? 0.0,
      json[Keys.ARG_TIME] ?? 0.0,
      isLocationMocked ?? false,
      json[Keys.ARG_PROVIDER] ?? "",
    );
  }

The problem was that the LocationDto.fromJson function silently stopped due to some null values. If you want the change to be permanent you should include the modified package in the "dependency_overrides:" section of the pubspec.yaml file.

I hope this helps!

**Comment by ritesh305** [comment]
@sinanhaci  why did you closed this issue as completed? did you find the solution? i could not. i tried what @hector1980 suggested but same issue.
