### ISSUE TITLE
Pedometer gives wrong steps on Android

### ISSUE THREAD

**Issue by rizzellodavide** [cph-cachet/flutter-plugins#54]
Hello,
I followed the example on the repository of pedometer and tried to launch the app.
It worked perfectly on iOS but on Android it gave me a wrong number of steps (many steps less than the steps of the Samsung Health App - ex. 125 steps against 1500 real steps). I tried it on different Android devices:
- Samsung Galaxy S7 Edge - Android 8.0.0;
- Samsung Galaxy A50 - Android 9;

flutter version:
- Flutter (Channel stable, v1.12.13+hotfix.5)
- Android toolchain - develop for Android devices (Android SDK version 29.0.2)
- Xcode - develop for iOS and macOS (Xcode 11.3.1)
- Android Studio (version 3.5)
- VS Code (version 1.41.1)

pedometer dependence declaration is:
pedometer: 1.0.0

Thank you

**Comment by thomasnilsson** [comment]
Hi, the steps returned by the Pedometer app is the number of steps since last boot-up, which is due to how it is implemented on Android. 

Google Fit is the number of steps taken on that particular day, and there may be cases where steps taken since bott-up is lower than the other or vice versa. 

The idea behind the pedometer plugin is to let application developers track steps without relying on Google Fit, which is somewhat cumbersome to set up, if only the steps are needed.
