### ISSUE TITLE
Could not build the precompiled application for the device.

### ISSUE THREAD

**Issue by primekhan555** [cph-cachet/flutter-plugins#666]
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'health/health-Swift.h' file not found
/Users/apple/.pub-cache/hosted/pub.dev/health-4.4.0/ios/Classes/HealthPlugin.m:1:8

what is the issue here please help

**Comment by bardram** [comment]
We seem to have the same problem in the Study App.

**Comment by SlimShadyIAm** [comment]
As @bardram mentioned, the `health` package relies on HealthKit and since that is native iOS code, the `health` plugin needs to be built as a dynamic framework. This is done by adding the `use_frameworks!` keyword to your `ios/Podfile`. You can see an example of how this can be done here: https://github.com/cph-cachet/flutter-plugins/blob/38519c137f2914b7e0854486058f35677154a03f/packages/health/example/ios/Podfile#L31
