### ISSUE TITLE
[Health 5.0.0] requestAuthorization stopped working

### ISSUE THREAD

**Issue by Pomis** [cph-cachet/flutter-plugins#696]
### Device / Emulator and OS
 - Device: Pixel 5
 - OS: Android 13

### The bug description
Dialog prompting user to select a Google account is not showing up on `requestAuthorization`. However, the returned value is `true`. Later on, when `hasPermissions` is called, it returns `false`

### To Reproduce
```
  void _testHealth() async {
    final health = HealthFactory();
    final types = [HealthDataType.MOVE_MINUTES, HealthDataType.WEIGHT];
  
    final isAuthorized = await health.requestAuthorization(types);
    print("isAuthorized: $isAuthorized");
  
    final hasPermissions = await health.hasPermissions(types); // HealthFactory.hasPermissions(types) on 4.6.0
    print("hasPermissions: $hasPermissions");
  }
```
5.0.0 output:
```
isAuthorized: true
hasPermissions: false
```
4.6.0 output: 
```
isAuthorized: true
hasPermissions: true
```

### Flutter Doctor output
```
roman@Romans-MBP activate-app % flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 12.5 21G72 darwin-arm64, locale en-EE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.77.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by erickr** [comment]
@Pomis  Is it not using the Health Connect in v5, and with v5 it should not use the oauth client id?

**Comment by hoffmatteo** [comment]
This problem seems to be related to the new HealthConnect implementation, specifically the healthConnectClient:
https://github.com/cph-cachet/flutter-plugins/blob/d6c5941ef9425b0c4cb03bcf6c4aa5d8f7432ab4/packages/health/android/src/main/kotlin/cachet/plugins/health/HealthPlugin.kt#L334
When commenting this line out in the HealthPlugin.kt file, the Google Fit authentication works as expected.
With it the activity for some reason is never set, and thus the requestAuthorization method fails.
I am looking into this issue further and will provide an update once I have a proper fix.
