### ISSUE TITLE
[Health 8.0.0] The equivalents of sleep data do not match iOS Health.

### ISSUE THREAD

**Issue by WsrMustafa** [cph-cachet/flutter-plugins#803]
### Device / Emulator and OS
 - Device: iPhone 11
 - OS: iOS  16.6

### Describe the bug
The health data shown on the iPhone and the data from the "health" package do not match. We import sleep data into the iOS health app via the Apple watch. Then we pull this data with the health package. But the data I added in the image below does not match. For example, when I want to access the SLEEP_REM data, it corresponds to the Deep data in the iOS health app. I'm not sure if this is a mistake or if this is what should have happened. I think SLEEP_REM should correspond to the REM data on iOS, SLEEP_DEEP should correspond to the Deep data on iOS. This applies to other data. Can you make a comeback by checking this?

### Screenshots
![healthPackage_8_0_0 ](https://github.com/cph-cachet/flutter-plugins/assets/144433030/0dc5fd34-e536-424f-b113-a81405efd031)

### Flutter doctor 
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.2.1 22D68 darwin-arm64, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

Thank you in advance.

**Comment by Kam5678** [comment]
Yeah same issue for me. The Sleep data doesn't seem to match up correctly on IOS

**Comment by hoffmatteo** [comment]
Thank you for the issue and description! The sleep stages should be parsed correctly now, it will be released in the upcoming release.

**Comment by phackford** [comment]
I am experiencing the same issue. My IOS deep sleep is displaying as REM. Has a fix been released?

**Comment by itsamk** [comment]
Same issue for me! Using a temporary fix at the application level. Hopefully gets fixed in a release soon.

**Comment by phackford** [comment]
> Same issue for me! Using a temporary fix at the application level. Hopefully gets fixed in a release soon.
what does your temp fix look like?

**Comment by itsamk** [comment]
> > Same issue for me! Using a temporary fix at the application level. Hopefully gets fixed in a release soon.
> > what does your temp fix look like?

Using the following mapping - 
Real : Flutter Health
Awake : Awake
Deep : REM
Core : Deep 
REM : [Absent currently]
Time_in_bed : [Still to debug and understand. If I query last 24 hours, it gives me about twice the amount of sleep, so might need to query a shorter window of time]

**Comment by itsamk** [comment]
I investigated and figured out the problem here.

Apple allows the following Sleep Types (Reference: [Health Kit Documentation](https://developer.apple.com/documentation/healthkit/hkcategoryvaluesleepanalysis))  : 
1. inBed : The user is in bed
2. awake: The user is awake
3. asleepCore: The user is in light or intermediate sleep
4. asleepDeep: The user is in deep sleep
5. asleepREM: The user is in REM sleep
6. asleepUnspecified: The user is asleep, but the specific stage isn't known. (_Possibly_ captured when the watch isn't used for sleep detection and sleep is logged manually or automatically based on phone usage)
Note: **asleep** is now deprecated.

Currently, the mapping for some of these in this package is incorrect. Refer this file - https://github.com/cph-cachet/flutter-plugins/blob/master/packages/health/ios/Classes/SwiftHealthPlugin.swift. 

Currently,
SLEEP_IN_BED - 0
SLEEP_ASLEEP - 1
SLEEP_AWAKE - 2
SLEEP_DEEP - 3
SLEEP_REM - 4

How it should be (corrections in **bold**) - 
SLEEP_IN_BED - 0
SLEEP_ASLEEP - 1 (sleepUnspecified in terms of HealthKit. Value is going to be zero when all sleep stages' data is available.)
SLEEP_AWAKE - 2
SLEEP_LIGHT - 3 (sleepCore in terms of HealthKit. This should be allowed as a data type similar to Android.)
**SLEEP_DEEP - 4**
**SLEEP_REM - 5** 

I am going to attempt this change and will raise a PR if that works.

**Comment by pkhivesara** [comment]
@itsamk Would be fantastic if you can help answer this query: https://github.com/cph-cachet/flutter-plugins/issues/985 :)
