### ISSUE TITLE
[Pedometer 4.0.1] Getting step count without a stream

### ISSUE THREAD

**Issue by Schamppu** [cph-cachet/flutter-plugins#810]
### Getting step count without a stream
Trying to implement a logic where we could pull step count without stream. I need this information from step counter when the app is launched. Current implementation needs a step event to pull the value from the stream.

### Additional information
Please help.

**Comment by bardram** [comment]
Hi!

I am a little bit desperate, so decided to contact you through here. I saw you were one of the collaborators of the Github repository, and found you email. 

I am using Flutter package Pedometer 4.0.1 for my game WalkScape, which uses real life steps to count progress in the game. Long story short, I am demoing the game on convention in a week. 

Everything works great with the plugin, but not getting steps when the game starts. Because the plugin uses a stream, it doesn't push an event if nothing is happening on the device. This makes it reallt difficult for me to "load" the steps that were gained while the app was closed when the game starts.

What I would need with the plugin is just some method to call, which would return me whatever value is currently on the pedometer API.

Sorry to contact you with mail directly, but it's a big moment for me and I'm desperate.

- Sami Pentti
