### ISSUE TITLE
[HEALTH] Remove support for Google Fit

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#974]
Since Google is no longer supporting Google Fit, we should remove support for it in the health package. This will help reduce the complexity in the code.

**Comment by davidpryor** [comment]
I am interested in potentially working on this, but I see it was assigned. Is this actively being worked on, or would you benefit from a contribution?

**Comment by yogeshButani** [comment]
hi @bardram @davidpryor
 i have also used health package to get the steps data from health connect. On IOS devices it's working good, taking data from apple health successfully but when comes in android, its always showing 0 steps, i have all the setup for Android, even not getting any type of error still showing 0 steps don't know why...all permissions are enabled, app is also showing inside health connect settings on device...don't know how the issue is occurring... please help

**Comment by SlimShadyIAm** [comment]
@yogeshButani we kindly ask that you refrain from posting about your issue on unrelated threads. I can see that you've created a couple of issues on our repo, if someone has a solution or advice to offer, they will comment there.
